version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./databases:/var/lib/mysql
    
  adminer:
    build: ./adminer 
    restart: always
    ports:
      - 6080:8080

  python:
    build: ./python